[features]
seeds = true
skip-lint = false
[programs.localnet]
faucet = "EtTeTRSJSRBBgm5nrmodadBpToGFrwWjo2syiVAjvjuT"
[programs.devnet]
faucet = "EtTeTRSJSRBBgm5nrmodadBpToGFrwWjo2syiVAjvjuT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/devenv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
